### ISSUE TITLE
"Find loadouts by class" on the homepage not filtering correctly

### ISSUE THREAD

**Issue by pmdredd** [drg-tools/karl.gg#222]
When you click the class filter button on the homepage the ?character= url parameter is being sent back however the filtering is not applied. For example, I click the gunner class under 'find loadouts by class':

![image](https://user-images.githubusercontent.com/29774542/120996719-7d7bbc80-c77e-11eb-87ba-035b8bd95ff5.png)

And I get redirected to the filtered class page (view? I've not used Vue before) with the correct character id passed in the url, however I can still see non-Gunner classes.

![image](https://user-images.githubusercontent.com/29774542/120996901-a9973d80-c77e-11eb-9a2a-d99b37566a45.png)

This happens with other classes too. I'm using Firefox 89, and I don't see any errors in the browser console or network tools so I don't think any of my add-ons are breaking it.

**Comment by Darthmaul** [comment]
Thank you for reporting, this should be a straightforward fix. I think this was a minor oversight in our latest release.
