### ISSUE TITLE
Browse Table displays secondary as the primary

### ISSUE THREAD

**Issue by Darthmaul** [drg-tools/karl.gg#226]
This was reported on discord, but also surfaced when I was investigating the preview page enhancements. 

See here:
![primary](https://user-images.githubusercontent.com/1916366/121249297-6d450980-c872-11eb-9e94-69fde0b65283.png)

Steps to reproduce:
1. Create a loadout with only a secondary weapon
2. Save

Actual Results:
1. You will see the secondary weapon displayed as the primary in the table

Expected Result: 
1. You will see the secondary weapon displayed as the secondary

This is entirely due to this logic:
https://github.com/drg-tools/karl.gg/blob/53fa2f8cba307a5a40e862b7bb32798a0684fdc1/app/Loadout.php#L149-L181

We need to probably re-work this, and potentially look at the table logic.
This impacts the preview page enhancements as well, as we currently don't have a reliable way to pull primary/secondary weapons.

**Comment by chaseconey** [comment]
Fixed in 727cf1f0
