### ISSUE TITLE
Preview page, bottom of class picture is being truncated

### ISSUE THREAD

**Issue by phg49389** [drg-tools/karl.gg#228]
This is a bug that has been noticed a couple of times independently, but this issue is being created to follow up on a conversation had last night.

When a user looks at a Preview page ([example](https://karl.gg/preview/3261)), in the top-right side of the page there is a picture of the class that the loadout is for. Ever since the visual refactor ( #195 ), the bottom third or so of the picture is being obscured by the yellow horizontal bar and its grey/blue margin.

Chase and Andrew were able to demonstrate in real-time how this is a CSS styling issue that will take some time to figure out and fix, and they asked me to make this issue so it doesn't get forgotten.

**Comment by Darthmaul** [comment]
Fixed in #232
