### ISSUE TITLE
Bug: loadout guide formatting not working 

### ISSUE THREAD

**Issue by Darthmaul** [drg-tools/karl.gg#254]
Reported on discord:
Currently untested from my side

Users are reporting bold text and other formatting items are not working when using the wisywig editor. Investigate and determine the issue please.

**Comment by chaseconey** [comment]
This bug has something to do with how we are pushing and pulling data into the store from the editor component. This function specifically:

https://github.com/drg-tools/karl.gg/blob/master/resources/js/components/MarkdownEditor.vue#L32-L37

**Comment by Darthmaul** [comment]
Latest functionality update: "Pressing the Bold button in the WYSIWYG editor menu does nothing; however, doing that via Ctrl+B actually applies the Bold to selected text."
Just to keep track of as we diagnose this

**Comment by Darthmaul** [comment]
PR is up for this, might need to do some reviews to finalize this

**Comment by Darthmaul** [comment]
Another PR up to try an all new library to fix this

**Comment by Darthmaul** [comment]
This should now be resolved via #273
