### ISSUE TITLE
Can't write in the Markdown editor

### ISSUE THREAD

**Issue by Bauke** [drg-tools/karl.gg#279]
Not exactly sure what the issue is, but the WYSIWYG editor works fine while the Markdown editor doesn't. If I write text in the WYSIWYG editor and then switch it will show that text in the preview but won't show anything on the left. I also can't write anything myself in the Markdown editor.

Tested on Firefox 96 and latest iOS Firefox and Safari.

![image](https://user-images.githubusercontent.com/19501722/150683397-db8566d1-c02b-45ab-8973-bb89ffb45cfe.png)

**Comment by Darthmaul** [comment]
Thanks very much for this report

We are expediting a PR that has been open for a little while, a few remaining tasks. This will re-vamp the markdown editor and hopefully fix all of the outstanding bugs. We will keep you posted once resolved, and I will keep this issue open until it's fixed.

Sorry for the inconvenience, but we really appreciate the report

**Comment by Darthmaul** [comment]
This should now be resolved via #273 
Let us know if it did not resolve your issue. Thanks!
