### ISSUE TITLE
Suggestion: Sort from High to Low for "Salutes" instead of currently from Low to High

### ISSUE THREAD

**Issue by amperag** [drg-tools/karl.gg#318]
Hey guys, a suggestion for an enhanced UX on karl.gg:

![image](https://user-images.githubusercontent.com/61867589/170838045-f87612ba-be3d-477f-a5ce-235ef377f9b5.png)

### Current
When wanting to see the highest "saluted" builds on karl.gg one currently has two click (1) once on salutes (which shows the least saluted builds) and then a (2) second time to finally get the builds with the most salutes.

(1) 
![image](https://user-images.githubusercontent.com/61867589/170838166-e4e72801-d34f-4d98-b5d5-d5e6b09d372c.png)

(2)
![image](https://user-images.githubusercontent.com/61867589/170838209-c5598a2b-27c6-4176-9c8f-974422f4c07e.png)

### Suggestion
Make it so that if a user clicks once (or the first time) one "salutes" the list is sorted from most to least salutes right away (solution 2).

Cheers.

PS: Awesome website, using it weekly!

**Comment by theblang** [comment]
@amperag The problem is, you can't make *only* Salutes be descending by default as that'd be inconsistent, and you can't assume that *every* column should be descending, so what do you do? Most likely just save the last sort and automatically apply it to future searches.

**Comment by theblang** [comment]
@Darthmaul @chaseconey Is this something you would accept a PR for? 

And side question, do you have any instructions for how to run PHP / `composer` locally using Docker?
