### ISSUE TITLE
Incorrect Stats Modification for Backfeeding Module

### ISSUE THREAD

**Issue by avilla9182** [drg-tools/karl.gg#331]
## Problem Description
I have a basic issue to report. I was making a loadout with `Backfeeding Module` for the Gunner's Coil Gun, and I noticed that it dropped damage down by 50 points. However, in game when compared to base with no perks or no OCs, it only drops it by 20 points. In addition, in-game increases ammo count by 320 but on karl.gg ammo is increased by 360. This was probably what the stats were in beta/U36 release but has since been changed.

_Edit_: I also noticed `Optimized Magnetic Circuit` skill has a +140% but I think it was recently updated to +150%

## Proposed Resolution
Please change the following stat modifications for `Backfeeding Module`:
* `Damage` modification: -50 -> -20
* `Max Ammo` modification: +360 -> +320

_Edit_:`Charge Speed` modification: +140% -> +150% for `Optimized Magnetic Circuit` perk

If you have any questions or concerns, please notify me. Thank you in advanced!

**Comment by phg49389** [comment]
Hey. I'll work on updating this in the next 2-3 days. My life has been crazy busy lately, haven't had capacity to keep the Karl.gg tooltips up to date.

There are several things that need to be updated, beyond what is listed in this issue.

**Comment by phg49389** [comment]
@avilla9182 I just finished a round of updating all of Karl.gg's tooltips, including Backfeeding Module. Take a look; if you see anything incorrect please reply to this GH issue or notify us in the DRG Community Tools discord server.

If you're satisfied, you can close this GH issue.

**Comment by Darthmaul** [comment]
Thanks very much Phil - really appreciate the hard work. I'll leave this open for a bit, and if we don't hear anything I'll close this issue.
