### ISSUE TITLE
New feature: Grenades / Throwables support

### ISSUE THREAD

**Issue by Darthmaul** [drg-tools/karl.gg#339]
Implement throwables / grenades.

Db support is there I think, otherwise would require some migrations and help from Chase on prod deploy.

Add controllers / models / etc for backend

Add crud controllers and configuration for admin panel

Add throwables to builder
Try to implement it within the existing paradigm we've built. 
Add throwables to preview page
Add icons to app bundle. Martin has provided in slack 

I think that's it. Data to be added eventually I think

**Comment by phg49389** [comment]
Yeah. Back when we first built the Karl.gg database from scripts, I did add some basic implementation of the current 12 throwables. That info would need to be updated before going to Prod, but the framework is there.

I'll start aggregating the current 12 Throwables' in-depth data, to have ready for data entry when the CRUD is set up.

**Comment by Darthmaul** [comment]
Started working on this. Should have an mvp ready sometime this week. Not anticipating any issues so far.

**Comment by Darthmaul** [comment]
Oh I also need to add a filter on Browse and maybe a column in the future. No column for now probably
