### ISSUE TITLE
Web API for accessing data

### ISSUE THREAD

**Issue by ljvmiranda921** [drg-tools/karl.gg#355]
Hi!

I am interested in doing a fun study of DRG Builds in Karl.GG (as I think they're representative of common builds for the game). I wonder if there's a way for me to access the data aside from manually scraping it from the website? Is there a Web API that I can send HTTP requests to?

Let me know if I missed anything, thanks for your awesome work!

**Comment by Darthmaul** [comment]
Hello, thanks for reaching out. 

We do have an unofficial API which I can grant you access to. It's not officially maintained, but we can help you get it setup and configured.

As long as you're just interested in some data browsing, I don't see any issues leveraging it. If you're trying to use this for a commercial product, I would like to discuss further. We would want to do some maintenance to ensure we have a production-ready platform if that is the case.

Looking forward to your feedback

Andrew

**Comment by Darthmaul** [comment]
Hi @ljvmiranda921 - are you still interested in leveraging our API? I can work with you help set that up - just please reference my note above.

**Comment by ljvmiranda921** [comment]
Hi @Darthmaul , sorry for the late reply. I think I'm Ok now. MeatShield provided me with a data dump for the different loadouts. That was very helpful! I'm not planning to use the data for some commercial product, more of a fun data science project. Thanks again, and I appreciate the team's work!

**Comment by Darthmaul** [comment]
No problem, thanks for the update. Glad to hear MeatShield could help, and I really enjoyed your analysis. Happy holidays

Andrew
