### ISSUE TITLE
Increase comment delete/edit timer

### ISSUE THREAD

**Issue by JohannesMP** [drg-tools/karl.gg#361]
I tried to delete a comment moments after I posted it, and while I selected the "delete" option from the hamburger menu, after the page refreshed the comment was still there and the edit/delete options disappeared. 

Looking at the [default config, the default delete and edit time seems to be 60 seconds](https://github.com/drg-tools/karl.gg/blob/6e6e0768b8e5cbc4a0a733bb2a32414349dc3646/packages/laravel-comments/config/comments.php#L24-L28).

I feel 60 seconds is just a bit restrictive for an edit/delete timeout, and that something like 5 minutes would be a better minimum, and ideally a comment should always be possible to delete, but show a "the user has deleted this comment" note.

**Comment by Darthmaul** [comment]
Thanks for the feedback. I honestly wasn't even aware there was this limitation, and I think it's perfectly valid to increase the duration of being able to edit/delete the comment.

Per your other suggestion as well, if the timer functionality remains, it would be nice to show some kind of timer to a user.

Personally, I prefer to always be able to edit/delete comments for users - I simply wasn't aware that it was limited like this today. We'll take a look at this and see how we could improve this. I'll update this issue with any findings.

Thanks for the suggestion
