### ISSUE TITLE
Comment edit/delete countdown

### ISSUE THREAD

**Issue by JohannesMP** [drg-tools/karl.gg#362]
Currently it is not exposed to the user that they only have [60 seconds to edit or delete a comment](https://github.com/drg-tools/karl.gg/blob/6e6e0768b8e5cbc4a0a733bb2a32414349dc3646/packages/laravel-comments/config/comments.php#L24-L28) after they posted it.

Additionally the 'edit' and 'delete' options are not dynamically removed after 60 seconds have elapsed, so it's possible to make a comment and have a page open for a few minutes, then realize that you wanted to make an edit or delete the comment, click the hamburger menu and see the option you want to perform, only for nothing to happen when you click that option and the page reloads. 

It feels like a bug, while it is actually an intended feature that just isn't intuitively presented to the user.

<br/>

Ideally there should be a small greyed out countdown next to the delete/edit option, which once it expires disables those buttons clientside. 

That way it is clear to the user that they only have a set amount of time to edit or delete their comments, and the user won't be confused why nothing happened when they clicked the option visible on their screen at the time.

**Comment by Darthmaul** [comment]
Hello - let's consolidate this feedback into your other issue https://github.com/drg-tools/karl.gg/issues/361

These are essentially the same points of feedback, so we'll continue the discussion there. Thanks!
