### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by Sirocco745** [drg-tools/karl.gg#378]
Exactly what the title says. I believe I've identified a potential issue with the karl.gg website related to user account security. However, a publicly available GitHub issue is clearly not the place to talk about such things. You can contact me at sirocco745@gmail.com, and I do think that this is a problem that could cause you guys some grief later on.

**Comment by Sirocco745** [comment]
Apologies for the ping, @chaseconey and @Darthmaul, but I wanted to make sure at least one of the developers who've done work here recently sees this, and you two are the most recent to commit to this.

**Comment by phg49389** [comment]
It has been seen. We're trying to sync up on our Slack to talk about it; our schedules are vastly different.

I'm not one of the devs, but I work with them and help maintain the website's data.

**Comment by Sirocco745** [comment]
Alright, thanks for confirming that. I was kind of worried this wouldn't be spotted, given the time since last commit.

**Comment by Sirocco745** [comment]
So when do you think I can get around to talking with someone, @phg49389? It's not impedingly urgent, but I only say that because karl.gg is a pretty small and niche website, therefore the chances of someone bothering to hack a DRG loadout website are low. But it should still be addressed.

**Comment by Sirocco745** [comment]
Talked it over with the developers over Discord, and I believe that the problem has been addressed sufficiently.
